### ISSUE TITLE
Do not return a 500 error when dns zone does not exist.

### ISSUE THREAD

**Issue by busilina** [stackitcloud/external-dns-stackit-webhook#16]
### Is your feature request related to a problem? Please describe.

If for some reason the dns zone does not exist (anymore), the webhook [returns InternalServerError ](https://github.com/stackitcloud/external-dns-stackit-webhook/blob/main/pkg/api/apply_changes.go#L35C27-L35C52). This causes the `external-dns` pod to come in a CrashLoop.

### Describe the solution you'd like

I think it would be better to just give a (maybe a `warn`) log. E.g., `dns zone missing` and just continue without an error. 

### Describe alternatives you've considered

As an alternative maybe it's more appropriate to return a NotFound error (I am not sure if the `external-dns` would still crash since this is an error as well).

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I'm not sure if this is a requirement from the `external-dns` itself, but I feel that this is a very hard error handling. And I would like to discuss this with you. Thanks for your effort!

**Comment by PatrickKoss** [comment]
I think we talked in person about it and come to conclusion we should adjust external dns for graceful error handling. If there are is still a problem, feel free to open the issue again.

**Comment by busilina** [comment]
Yes, we already have opened a [PR](https://github.com/kubernetes-sigs/external-dns/pull/4319) in external-ds to handle this. This would solve our problem once merged. Thanks for the discussion.
